services:
  # Laravel dashboard container (new Laravel/Livewire dashboard)
  laravel-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    container_name: linkedin-laravel-dashboard
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=linkedin_jobs
      - DB_USERNAME=root
      - DB_PASSWORD=
      - APP_ENV=development
      - APP_DEBUG=true
    ports:
      - "8082:80"  # Laravel dashboard
    volumes:
      - ./laravel-dashboard:/var/www/html
    # Remove user mapping - let Docker handle permissions
    restart: unless-stopped
    networks:
      - linkedin-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: linkedin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "linkedin_jobs"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "laravelpass"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/laravel-init.sql:/docker-entrypoint-initdb.d/laravel-init.sql
      - ./backups:/backups
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    restart: unless-stopped
    networks:
      - linkedin-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: linkedin-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - linkedin-network

networks:
  linkedin-network:
    driver: bridge

volumes:
  mysql_data:

