services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev   # or Dockerfile.prod
    ports:
      - "8082:80"
    volumes:
      - ./laravel-dashboard:/var/www/html   # hot-reload code
      - ~/.composer/cache:/tmp/composer     # speeds up rebuilds
      - ./backups:/var/www/backups         # backup SQL files
    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: linkedin_jobs
      DB_USERNAME: laravel
      DB_PASSWORD: laravelpass
    depends_on:
      db:
        condition: service_healthy
    networks: [ internal ]

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: linkedin_jobs
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ internal ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: [ "8080:80" ]
    environment:
      PMA_HOST: db
    depends_on: [ db ]
    networks: [ internal ]

networks:
  internal:

volumes:
  mysql_data: